version: '3.9'

services:
  spam_api:
    build:
      context: ./fastapi_app
      dockerfile: Dockerfile
    command: uvicorn spam:app --host 0.0.0.0 --port 8001
    volumes:
      - ./fastapi_app:/app
    expose:
      - 8001

  trash_api:
    build:
      context: ./fastapi_app
      dockerfile: Dockerfile
    command: uvicorn trash:app --host 0.0.0.0 --port 8002
    volumes:
      - ./fastapi_app:/app
    expose:
      - 8002

  cifar_api:
    build:
      context: ./fastapi_app
      dockerfile: Dockerfile
    command: uvicorn cifar:app --host 0.0.0.0 --port 8003
    volumes:
      - ./fastapi_app:/app
    expose:
      - 8003

  main_api:
    build:
      context: ./fastapi_app
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8004
    volumes:
      - ./fastapi_app:/app
    expose:
      - 8004

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/portfolio.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - spam_api
      - trash_api
      - cifar_api
      - main_api
