# Generated by Django 4.2.11 on 2025-09-23 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "barcode",
                    models.CharField(
                        help_text="The unique barcode (EAN/UPC) of the product.",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the product.", max_length=255
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True,
                        help_text="The brand name of the product.",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="A URL to an image of the product.",
                        max_length=500,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        default="Uncategorized",
                        help_text="Category of the product, e.g., Dairy, Produce.",
                        max_length=100,
                    ),
                ),
                (
                    "rack_zone",
                    models.CharField(
                        blank=True,
                        help_text="Location in the supermarket, e.g., Aisle 5, R3.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1, help_text="The number of units for this item batch."
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        help_text="The expiration date of this item batch."
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time this item was added to the inventory.",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_items",
                        to="Inventory.product",
                    ),
                ),
            ],
            options={"ordering": ["expiry_date"],},
        ),
    ]
