# Generated by Django 5.0.7 on 2025-01-30 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataScienceProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the project', max_length=200)),
                ('image', models.ImageField(upload_to='Datascience/')),
                ('description', models.TextField(help_text='Brief description of the project')),
                ('dataset_name', models.CharField(help_text='Name of the dataset used', max_length=200)),
                ('popularity', models.PositiveIntegerField(default=0, help_text='Popularity of the project')),
                ('dataset_description', models.TextField(help_text='Details about the dataset')),
                ('dataset_source', models.URLField(blank=True, help_text='URL link to the dataset, if available')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DashboardMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Title of the metric (e.g., 'New Users')", max_length=200)),
                ('icon', models.CharField(help_text="Icon identifier for the metric (e.g., 'mingcute:user-follow-fill')", max_length=200)),
                ('value', models.PositiveIntegerField(default=0, help_text="Numeric value of the metric (e.g., '15000')")),
                ('description', models.CharField(blank=True, help_text='Short description of the metric (optional)', max_length=500)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DashboardMetric', to='analytics.datascienceproject')),
            ],
        ),
        migrations.CreateModel(
            name='EDA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='Null', help_text='Details of the EDA analysis')),
                ('analysis_type', models.CharField(choices=[('univariate', 'Univariate'), ('bivariate', 'Bivariate'), ('multivariate', 'Multivariate'), ('others', 'others')], help_text='Type of EDA analysis', max_length=50)),
                ('popularity', models.PositiveIntegerField(default=0, help_text='Popularity of the project')),
                ('img', models.ImageField(upload_to='EDA/')),
                ('analysis_details', models.TextField(help_text='Details of the EDA analysis')),
                ('insights', models.TextField(help_text='Insights derived from this EDA')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eda', to='analytics.datascienceproject')),
            ],
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text='Name of the ML model used', max_length=200)),
                ('popularity', models.PositiveIntegerField(default=0, help_text='Popularity of the project')),
                ('img', models.ImageField(blank=True, upload_to='ML/')),
                ('training_details', models.TextField(help_text='Details about how the model was trained')),
                ('evaluation_metrics', models.TextField(help_text='Evaluation metrics for the model')),
                ('insights', models.TextField(help_text='Key insights from the ML model')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_models', to='analytics.datascienceproject')),
            ],
        ),
    ]
