# Generated by Django 5.0.7 on 2025-02-03 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eda',
            name='chart_type',
            field=models.CharField(blank=True, choices=[('histogram', 'Histogram'), ('boxplot', 'Boxplot'), ('scatterplot', 'Scatter Plot'), ('barchart', 'Bar Chart'), ('countplot', 'Count Plot'), ('violinplot', 'Violin Plot'), ('heatmap', 'Heatmap'), ('pairplot', 'Pair Plot'), ('linechart', 'Line Chart'), ('piechart', 'Pie Chart'), ('kdeplot', 'KDE Plot'), ('swarmplot', 'Swarm Plot'), ('others', 'Others')], help_text='Type of chart used in EDA', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eda',
            name='col_size',
            field=models.CharField(blank=True, choices=[('col-4', 'col-4'), ('col-6', 'col-6'), ('col-8', 'col-8'), ('col-12', 'col-12')], help_text='size of the column', max_length=50, null=True),
        ),
    ]
