# Generated by Django 5.0.7 on 2025-03-30 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_eda_chart_type_eda_col_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='training_details',
            field=models.URLField(blank=True, help_text='Add url of Prediction Url', null=True),
        ),
    ]
