# Generated by Django 5.2 on 2025-05-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0003_alter_mlmodel_training_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datascienceproject",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
