# Generated by Django 5.2 on 2025-07-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0004_alter_datascienceproject_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="datascienceproject",
            name="challenges_faced",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="datascienceproject",
            name="methodology",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="datascienceproject",
            name="objective",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="datascienceproject",
            name="problem",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="datascienceproject",
            name="result",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="datascienceproject",
            name="solution",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="datascienceproject",
            name="technologies_used",
            field=models.TextField(blank=True, null=True),
        ),
    ]
