# Generated by Django 4.2.11 on 2025-03-30 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SEOSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("Home", "Home"),
                            ("About Us", "About Us"),
                            ("Service", "Service"),
                            ("Contact", "Contact"),
                        ],
                        max_length=100,
                    ),
                ),
                ("meta_keywords", models.CharField(max_length=255)),
                ("meta_description", models.TextField()),
            ],
        ),
    ]
