server {
    listen 80;

    location /spam/ {
        proxy_pass http://spam_api:8001/;
    }

    location /trash/ {
        proxy_pass http://trash_api:8002/;
    }

    location /cifar/ {
        proxy_pass http://cifar_api:8003/;
    }

    location /main/ {
        proxy_pass http://main_api:8004/;
    }
}
