# Generated by Django 4.1 on 2024-02-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutMe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("img", models.ImageField(null=True, upload_to="about/")),
                ("birthday", models.DateField()),
                ("degree", models.CharField(max_length=100)),
                ("experience", models.IntegerField()),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.CharField(max_length=255)),
                ("freelance_available", models.BooleanField(default=False)),
                ("bio", models.TextField()),
            ],
        ),
    ]
