# Generated by Django 4.1 on 2024-02-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutme",
            name="title",
            field=models.CharField(default="Developer", max_length=200),
            preserve_default=False,
        ),
    ]
