# Generated by Django 4.1 on 2024-02-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_aboutme_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(max_length=100)),
                ("company", models.CharField(max_length=100)),
                ("date_range", models.CharField(max_length=20)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Qualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("degree", models.CharField(max_length=100)),
                ("institution", models.CharField(max_length=100)),
                ("date_range", models.CharField(max_length=20)),
                ("description", models.TextField()),
            ],
        ),
    ]
