# Generated by Django 4.1 on 2024-02-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_experience_qualification"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("percentage", models.IntegerField()),
                (
                    "progress_bar_color",
                    models.CharField(
                        choices=[
                            ("bg-primary", "Primary"),
                            ("bg-secondary", "Secondary"),
                            ("bg-success", "Success"),
                            ("bg-danger", "Danger"),
                            ("bg-warning", "Warning"),
                            ("bg-info", "Info"),
                            ("bg-dark", "Dark"),
                        ],
                        default="bg-primary",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
