# Generated by Django 4.1 on 2024-02-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_skill"),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="portfolio/")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("design", "Web Design"),
                            ("course", "Course"),
                            ("book", "Book"),
                            ("media", "Media"),
                            ("others", "Others"),
                        ],
                        default="others",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
