# Generated by Django 4.1 on 2024-02-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_portfolio"),
    ]

    operations = [
        migrations.RenameField(
            model_name="portfolio", old_name="image", new_name="img",
        ),
        migrations.AddField(
            model_name="portfolio",
            name="background_color",
            field=models.CharField(default="bg-primary", max_length=20),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
