# Generated by Django 4.1 on 2024-02-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_rename_image_portfolio_img_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("icon_class", models.CharField(default="fa-laptop", max_length=50)),
                ("description", models.TextField()),
            ],
        ),
        migrations.RemoveField(model_name="portfolio", name="background_color",),
    ]
