# Generated by Django 4.1 on 2024-02-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_service_remove_portfolio_background_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="order_number",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="qualification",
            name="order_number",
            field=models.IntegerField(null=True),
        ),
    ]
