# Generated by Django 4.2.11 on 2024-08-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0009_portfolio_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutme",
            name="cv",
            field=models.FileField(blank=True, null=True, upload_to="cv/"),
        ),
    ]
