# Generated by Django 4.2.11 on 2024-08-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0010_aboutme_cv"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutme",
            name="video_profile",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
