# Generated by Django 5.0.7 on 2025-03-30 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_aboutme_facebook_aboutme_github_aboutme_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='popularity',
            field=models.IntegerField(blank=True, default=0, help_text='Indicates the popularity of the portfolio item', null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.CharField(choices=[('design', 'Web Design'), ('course', 'Course'), ('Data Science', 'Data Science'), ('media', 'Media'), ('others', 'others')], default='others', max_length=20),
        ),
    ]
