# Generated by Django 5.2 on 2025-07-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0013_portfolio_popularity_alter_portfolio_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tools",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("percentage", models.IntegerField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("programming", "Programming Languages"),
                            ("devops", "DevOps"),
                            ("visualization", "Visualization"),
                            ("database", "Databases"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "progress_bar_color",
                    models.CharField(
                        choices=[
                            ("bg-primary", "Primary"),
                            ("bg-secondary", "Secondary"),
                            ("bg-success", "Success"),
                            ("bg-danger", "Danger"),
                            ("bg-warning", "Warning"),
                            ("bg-info", "Info"),
                            ("bg-dark", "Dark"),
                        ],
                        default="bg-primary",
                        max_length=20,
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="tools/")),
            ],
        ),
    ]
