# Generated by Django 5.2 on 2025-07-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0014_tools"),
    ]

    operations = [
        migrations.AddField(
            model_name="tools",
            name="popularity",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Indicates the popularity of the Tool",
                null=True,
            ),
        ),
    ]
