# Generated by Django 5.2 on 2025-07-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0015_tools_popularity"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="challenges_faced",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="methodology",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="objective",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="problem",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="result",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="solution",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="technologies_used",
            field=models.TextField(blank=True, null=True),
        ),
    ]
