# Generated by Django 5.2 on 2025-07-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0016_portfolio_challenges_faced_portfolio_methodology_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tools",
            name="category",
            field=models.CharField(
                choices=[
                    ("programming", "Programming"),
                    ("web", "Web & Frameworks"),
                    ("ml", "ML/DL"),
                    ("data_tools", "Data Tools"),
                    ("nlp", "NLP"),
                    ("deployment", "Deployment"),
                    ("database", "Databases"),
                    ("cloud_devops", "Cloud & DevOps"),
                    ("others", "others"),
                ],
                max_length=20,
            ),
        ),
    ]
