# Generated by Django 4.2.11 on 2024-08-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutMe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=100)),
                ("img", models.ImageField(null=True, upload_to="about/")),
                ("birthday", models.DateField()),
                ("degree", models.CharField(max_length=100)),
                ("experience", models.IntegerField()),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.CharField(max_length=255)),
                ("freelance_available", models.BooleanField(default=False)),
                ("bio", models.TextField()),
                ("cv", models.FileField(blank=True, null=True, upload_to="cv/")),
                (
                    "video_profile",
                    models.URLField(blank=True, max_length=255, null=True),
                ),
                ("github", models.URLField(blank=True, max_length=255, null=True)),
                ("linkedin", models.URLField(blank=True, max_length=255, null=True)),
                ("instagram", models.URLField(blank=True, max_length=255, null=True)),
                ("facebook", models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(max_length=100)),
                ("company", models.CharField(max_length=100)),
                ("date_range", models.CharField(max_length=20)),
                ("description", models.TextField()),
                ("order_number", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Qualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("degree", models.CharField(max_length=100)),
                ("institution", models.CharField(max_length=100)),
                ("date_range", models.CharField(max_length=20)),
                ("description", models.TextField()),
                ("order_number", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("icon_class", models.CharField(default="fa-laptop", max_length=50)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("percentage", models.IntegerField()),
                (
                    "progress_bar_color",
                    models.CharField(
                        choices=[
                            ("bg-primary", "Primary"),
                            ("bg-secondary", "Secondary"),
                            ("bg-success", "Success"),
                            ("bg-danger", "Danger"),
                            ("bg-warning", "Warning"),
                            ("bg-info", "Info"),
                            ("bg-dark", "Dark"),
                        ],
                        default="bg-primary",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
