# Generated by Django 5.2 on 2025-05-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PythONFire", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pythonproject",
            name="code",
            field=models.TextField(blank=True, null=True),
        ),
    ]
