# Generated by Django 5.2 on 2025-05-28 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PythONFire", "0002_pythonproject_code"),
    ]

    operations = [
        migrations.RemoveField(model_name="pythonproject", name="code",),
        migrations.AddField(
            model_name="pythonproject",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                default="easy",
                max_length=10,
            ),
        ),
    ]
